### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by SrBrahma** [ishaan6395/react-leaflet-enhanced-marker#3]
./node_modules/react-leaflet-enhanced-marker/lib/Markers.js
Module not found: Can't resolve 'fbjs/lib/areEqual' in '/...XYZ.../node_modules/react-leaflet-enhanced-marker/lib'

**Comment by ishaan6395** [comment]
Which version of react are you using? I believe the react version is causing an issue. This package is compatible with react 16.3+

**Comment by schniddsel** [comment]
This has nothin to do with the React version. You have to include the package in your dependencies. There are none installed

**Comment by chris241** [comment]
I have this error then build 
![Capture](https://user-images.githubusercontent.com/52663375/117643723-5f2b9c80-b191-11eb-837e-c917d252c6f3.PNG)
