### ISSUE TITLE
Can't resolve 'fbjs/lib/areEqual'

### ISSUE THREAD

**Issue by makhataibar** [ishaan6395/react-leaflet-enhanced-marker#6]
Module not found: Can't resolve 'fbjs/lib/areEqual' in ...

**Comment by karl-run** [comment]
I'm also getting this. Seems like [fbjs](https://www.npmjs.com/package/fbjs) is missing as a direct dependency of the lib.

**Comment by abettermap** [comment]
Same here. Installing `fbjs` fixed it for me.

Duplicate of #3.
